### ISSUE TITLE
`initial_value()` not working as expected, returning None 

### ISSUE THREAD

**Issue by adamJLev** [rsinger86/django-lifecycle#11]
Using this quite simple code:

```
In [13]: m = SomeModel.objects.last()

In [14]: m.initial_value('status')
>> None 

In [15]: m.status = 'foo'

In [18]: m.initial_value('status')
>> 'active'
```

I noticed that the `initial_value` method returns None on any field unless the value has been changed, which seems like a bug.

**Comment by rsinger86** [comment]
Agreed. Thanks for pointing this out.

**Comment by rsinger86** [comment]
This should be fixed in latest release. Thanks again.
