### ISSUE TITLE
Move 'urlman' library as a test requirement

### ISSUE THREAD

**Issue by DmytroLitvinov** [rsinger86/django-lifecycle#112]
`urlman` package is used inside `tests/` folder which is not included in PyPI release. 
We need to move `urlman` from `install_requires` to `tests_require`

**Comment by DmytroLitvinov** [comment]
The problem that it is included in my requirements.txt file when I tried to compile package with `pip-tools` but it is not used in the package itself, only used for testing.

**Comment by DmytroLitvinov** [comment]
I am ready to provide PR in case maintainers approve that work.

**Comment by EnriqueSoria** [comment]
> I am ready to provide PR in case maintainers approve that work.

If you're still open to do it, make a PR and we'll merge it.

**Comment by DmytroLitvinov** [comment]
Hi @EnriqueSoria ,
Here it is https://github.com/rsinger86/django-lifecycle/pull/133
