### ISSUE TITLE
Django 4.x support

### ISSUE THREAD

**Issue by Archmonger** [rsinger86/django-lifecycle#114]
Currently, Django 4.x is not tested within `tox.ini`.

Best to update this and check if there are any bugs surrounding Django 4.

**Comment by peter-stuart-turner** [comment]
There are - sometimes, after an AFTER_SAVE hook is triggered, a db_task is not able to access the object by PK.

Serious one - but not sure of the root cause, will be investigating it with @jacoduplessis

**Comment by jacoduplessis** [comment]
> There are - sometimes, after an AFTER_SAVE hook is triggered, a db_task is not able to access the object by PK.
> 
> Serious one - but not sure of the root cause, will investigate it (perhaps with @jacoduplessis)

You need to add on_commit=True in your hook config. See #97.
