### ISSUE TITLE
AFTER_DELETE hook not triggered on when admin page "Delete selected objects" is used on the list view

### ISSUE THREAD

**Issue by Kazhuu** [rsinger86/django-lifecycle#142]
We used this neat library to add AFTER_DELETE hook to our child model to delete parent object automatically when all it's child objects are deleted. After some debugging we noticed that if models are deleted individually, the hook gets called as expected. However it seems if the admin page "delete selected objects" action is used on the list view even for one object. The hook doesn't seem to get called at all. Is this a bug or known issue? If this is a bug I'd be happy to contribute a solution to this because we need this behavior. If this is something that cannot be addressed meaningful way, maybe adding a note about this to the documentation would be a good thing to do.

What do you think? And thanks for this amazing library!

EDIT: Okay I browsed through the closed issues and found this https://github.com/rsinger86/django-lifecycle/issues/74. It seems this is a limitation from Django side. Should this be something added to the docs somewhere, so this does not necessarily comes as a surprise or the user thinks this is not a bug in the library?

**Comment by EnriqueSoria** [comment]
Yes, we should add a "common gotchas" in the documentation.

For your use case you could override [ModelAdmin.delete_queryset](https://docs.djangoproject.com/en/4.2/ref/contrib/admin/#django.contrib.admin.ModelAdmin.delete_queryset) so it performs deletion using model's delete, as suggested [in the django docs](https://docs.djangoproject.com/en/4.2/ref/contrib/admin/actions/)

**Comment by Kazhuu** [comment]
Okay thanks for the prompt reply. This issue can be closed :+1:
