### ISSUE TITLE
many to many changes

### ISSUE THREAD

**Issue by Zerotask** [rsinger86/django-lifecycle#146]
We encountered a problem which occurs with a many to many relationship (User groups). Every time a user is changed or created, we want to check if one of 2 mandatory groups are set. Using a regular signal / this package doesn't seem to work, because m2m are updated afterwards, see https://stackoverflow.com/questions/41574022/adding-user-to-group-on-save-in-django-1-9

Therefore it would be a great addition to have a hook to enable this behavior.

**Comment by EnriqueSoria** [comment]
Have you checked this?

https://github.com/rsinger86/django-lifecycle/issues/120
