### ISSUE TITLE
What is django_lifecycle_checks? And can it also perhaps be added to the main codebase? 

### ISSUE THREAD

**Issue by TonisPiip** [rsinger86/django-lifecycle#147]
ref: https://github.com/rsinger86/django-lifecycle/blob/master/django_lifecycle_checks/apps.py

It seems to catch some gotchas, and it could also easily catch this issue https://github.com/rsinger86/django-lifecycle/issues/96 by checking the MRO of the models, to ensure that the mixin isn't in the end of the MRO. 

I would make a PR to add that, but I don't see how this code is being used anywhere for end-users.  

I guess it would require having it being added to INSTALLED_APPS, but that's no really a deal breaker for such a helpful tool as this. :thinking:

**Comment by EnriqueSoria** [comment]
This app adds a check that raises an exception if you add a hook in a model which doesn't inherit from `LifecycleModelMixin`.

It has been added recently, and there's a short explanation in the docs on how to enable it (because it's an opt-in feature): https://rsinger86.github.io/django-lifecycle/#optional-add-django_lifecycle-to-your-installed_apps

About this gotcha #96, I think we can't add a check to avoid this because someone may want to add some mixin preceding `LifecycleModelMixin`.

**Comment by TonisPiip** [comment]
> because someone may want to add some mixin preceding LifecycleModelMixin.

Yes, but they for sure aren't wanting to have the base django model be above the mixin in the MRO.
As in that case model.save() will be run first, and since that doesn't ever call super, the mixin's save will never be run. It's a valid check.

**Comment by TonisPiip** [comment]
Ah, yes seems that I'm using an older version of the lifecycle hooks which is why `django_lifecycle_checks` isn't a valid django app. But the doc is wrong there, title says to add `django_lifecycle` not `django_lifecycle_checks`

**Comment by EnriqueSoria** [comment]
> > because someone may want to add some mixin preceding LifecycleModelMixin.
> 
> Yes, but they for sure aren't wanting to have the base django model be above the mixin in the MRO. As in that case model.save() will be run first, and since that doesn't ever call super, the mixin's save will never be run. It's a valid check.

Maybe we could check that `LifecycleModelMixin` comes before `models.Model`. Do you want to implement it yourself? If not I could do it when have some spare time.

**Comment by EnriqueSoria** [comment]
> Ah, yes seems that I'm using an older version of the lifecycle hooks which is why `django_lifecycle_checks` isn't a valid django app. But the doc is wrong there, title says to add `django_lifecycle` not `django_lifecycle_checks`

True! If you want, do a PR fixing that so we can give credit to you

**Comment by TonisPiip** [comment]
Sure, I can try to do it at some point, 

there's also another issue which I fixed by extending the app rather than forking, the issue with update_fields insave, ideally that should be fixed in the project too. (issue being in `django?>=4`  update_or_create() it calls save() on the model, but with a dynamically created list of fields, so if you have a hook which modifies any other field, then that change doesn't get saved. what I did was put a update_fields kwarg into the hook config which will inject those fields into the save. 

I was in a hurry so I don't know if that is a known / fixed issues in later version or whatever.

**Comment by EnriqueSoria** [comment]
> Sure, I can try to do it at some point,
> 
> there's also another issue which I fixed by extending the app rather than forking, the issue with update_fields insave, ideally that should be fixed in the project too. (issue being in `django?>=4` update_or_create() it calls save() on the model, but with a dynamically created list of fields, so if you have a hook which modifies any other field, then that change doesn't get saved. what I did was put a update_fields kwarg into the hook config which will inject those fields into the save.
> 
> I was in a hurry so I don't know if that is a known / fixed issues in later version or whatever.

This hasn't been fixed yet, there's an open issue (in fact you opened it!) #136
