### ISSUE TITLE
Use of deepcopy to capture mutable field-changes breaks some models

### ISSUE THREAD

**Issue by ggainey** [rsinger86/django-lifecycle#155]
Recent attempt to update from django-lifecycle/1.1.2 to 1.2.3 broke our app in ways that we can't fix.

Specifically, [this change](https://github.com/rsinger86/django-lifecycle/pull/151/files#diff-ccd0462c3332b1460bdeefa901260186d8b9de888e6acd16c6d63a0fbbbe2c27R85) breaks us because the entity that is now being `deepcopied` isn't pickle-able.

You can see the failure in the [failed dependabot run](https://github.com/pulp/pulpcore/pull/5093#issuecomment-1978533424) Specifically, the error is: `failed (cannot pickle 'Context' object)`

For now, we're going to have to pin django-lifecycle to 1.2.

**Comment by aschmitz-wbd** [comment]
We noticed a similar problem with models that use file fields. `TypeError: cannot pickle 'BufferedRandom' instances`

**Comment by EnriqueSoria** [comment]
Solved in #161, which will be included in version 1.2.4
