### ISSUE TITLE
refresh_from_db doesn't update the initial state

### ISSUE THREAD

**Issue by partizaans** [rsinger86/django-lifecycle#157]
Hi!
When calling `refresh_from_db()` on a model instance, the values are reloaded from the database. However, the `_initial_state` stored on a `LifeCycleModel` instance is not recalculated. If the maintainers consider this a bug, I can provide a fix by overriding the `refresh_from_db` method in the library Mixin.

**Comment by EnriqueSoria** [comment]
That makes sense to me
