### ISSUE TITLE
Question: Does it work with bulk methods? 

### ISSUE THREAD

**Issue by felippemr** [rsinger86/django-lifecycle#18]

**Comment by rsinger86** [comment]
No, it does not. Django bulk update/delete methods (as far as I know) optimize for efficiency, do not load database models into memory, and do not call the model save() method.

If you would like to bulk update/delete models with hooks, you could add a custom manager method that first filters and loads the models, iterates over them, and calls delete/save on each one.

**Comment by felippemr** [comment]
Thank you!
