### ISSUE TITLE
Lifecycle hook not triggered

### ISSUE THREAD

**Issue by sondrelg** [rsinger86/django-lifecycle#36]
Hi,

I've just tried implementing django-lifecycle into my project, but I'm having a hard time getting started.

My model looks like this:

```python
class MyModel(LifecycleModel):
    ...
    model = models.CharField(max_length=200)
    ...

    @hook('before_update', when='model', has_changed=True)
    def on_content_change(self):
        self.model = 'test'
```

for some reason, the hook doesn't seem to be triggered. I've also tried stacking decorators to include other `moments` with the same result.

Conversely, this works:

```python
class MyModel(LifecycleModel):
    ...
    model = models.CharField(max_length=200)
    ...

    def save(self, *args, **kwargs):
        self.model = 'test'
        super(MyModel, self).save(*args, **kwargs)
```

Am I missing something in my implementation? I'm on Django 2.2.8, python 3.7, and django-lifecycle 0.7.1.

**Comment by rsinger86** [comment]
How are you saving/updating your instance of `MyModel`? Certain types of updates, ie bulk updates where the model instances are not loaded into memory, will not work. If you could post a full code example, it would help me debug this.

**Comment by sondrelg** [comment]
Good point; I believe we were using `get_or_create` or `update_or_create`. I'll test using .save and update the issue once I get to work in a bit.

**Comment by sondrelg** [comment]
Here's an example model

```python
class Companies(LifecycleModel):
    GUID = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=200)
    registered = models.DateTimeField(blank=True, null=True, auto_now_add=True)
    modified = models.DateTimeField(blank=True, null=True, auto_now=True)

    @hook('before_update', when='model', has_changed=True)
    def on_content_change(self):
        self.name = 'test'

    class Meta:
        db_table = 'Companies'
```

and here is me testing with a clean DB
```shell script
In [1]: from deployment.models import Companies
In [2]: c = Companies.objects.create(name='thisIsWrong')
In [3]: c.name
Out[3]: 'thisIsWrong'
In [4]: 
In [4]: comp = Companies.objects.get(name='thisIsWrong')
In [5]: comp.name = 'test2'
In [6]: comp.save()
In [7]: 
In [7]: company = Companies.objects.get(name='test2')  # this should fail
In [8]: company.name
Out[8]: 'test2'
```

I'll be the first to say my implementation might be incorrect. How would I set up the hook to edit the format of an incoming variable on all writes to the DB? I'm taking in PC model names which can get very long, and have create a regex to strip them down - I want to run this on any incoming model data before it's saved to the DB.

**Comment by samitnuk** [comment]
@sondrelg
Please review PR #37 where you can see examples of `before_create` and `before_update` hooks using.

**Comment by rsinger86** [comment]
The test in your pull request #37  is passing for me. I see a typo in the example code you posted earlier in this read, however. Specifically, the value passed to `when` should be "name" NOT "model".

```python
class Companies(LifecycleModel):
    GUID = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=200)
    registered = models.DateTimeField(blank=True, null=True, auto_now_add=True)
    modified = models.DateTimeField(blank=True, null=True, auto_now=True)

    @hook('before_update', when='model', has_changed=True)
    def on_content_change(self):
        self.name = 'test'

    class Meta:
        db_table = 'Companies'
```

**Comment by sondrelg** [comment]
Thank you @rsinger86 and @samitnuk; the examples provided in PR #37 work well, so I'll implement them to our project now. Really appreciate the help :)
