### ISSUE TITLE
How to deal with save(update_fields=['foo', bar']) ?

### ISSUE THREAD

**Issue by konstunn** [rsinger86/django-lifecycle#43]
Hi, thanx for a very interesting alternative to django signals!

Does you package tackle with save(update_fields=[..]) the right way? Fo example I changed two fields on the instance, then I called save(update_fields=['field1', 'field2']) and earlier I declared a hook to update some field3 on field1, field2 updates. Will field3 be updated despite of update_fields kwarg in save()?

**Comment by nocl1p** [comment]
In case update_fields=['field1', 'field2'] hooks in your model will be able to watch only these fields 'field1', 'field2'. I've already came across this thing.
