### ISSUE TITLE
LifecycleModelMixin returns None for delete

### ISSUE THREAD

**Issue by oaosman84** [rsinger86/django-lifecycle#66]
By default, Django's ORM has a return value for `delete()`, as per: https://docs.djangoproject.com/en/3.1/ref/models/querysets/#django.db.models.query.QuerySet.delete

It looks like `LifecycleModelMixin`'s code is:
```
    def delete(self, *args, **kwargs):
        self._run_hooked_methods(BEFORE_DELETE)
        super().delete(*args, **kwargs)
        self._run_hooked_methods(AFTER_DELETE)
```

Hence, it returns `None` in the absence of any AFTER_DELETE hooks.

If this is not intended, happy to open a PR to fix. Seems like we should not change the return value of delete.

**Comment by rsinger86** [comment]
This is fixed in the latest release. Thank you for noting it.
