### ISSUE TITLE
changes on related models don't trigger the hooked methods

### ISSUE THREAD

**Issue by zahersarieddine** [rsinger86/django-lifecycle#68]
I think you SHOULD update the documentation because it caused me to waste lot of time trying to figure out why foreign keys triggers are not working before reading that you don't support that and are not planning to do that either.

**Comment by fabiocaccamo** [comment]
I have the same problem, it would be a great improvement.

**Comment by EnriqueSoria** [comment]
> @EnriqueSoria thanks for your reply, but after more than a year since my comment I don't remember anymore the exact problem/scenario.

haha understandable... anyway, I had to try

**Comment by fabiocaccamo** [comment]
I try to recover some info, I left some comments in a private project.

**Comment by fabiocaccamo** [comment]
I may be wrong, but i think that the problem is that hooks don't work as expected when the watched field (`parent` in the example below) is a `ForeignKey`.

```python
@hook(AFTER_SAVE, when="parent", was="")
def update_when_parent_is_set(self):
    # do stuff
    pass 
```

So, if the functionality is not fully supported, an error should be raised to avoid unnecessary debugging.

**Comment by EnriqueSoria** [comment]
> I may be wrong, but i think that the problem is that hooks don't work as expected when the watched field (`parent` in the example below) is a `ForeignKey`.
> 
> ```python
> @hook(AFTER_SAVE, when="parent", was="")
> def update_when_parent_is_set(self):
>     # do stuff
>     pass 
> ```
> 
> So, if the functionality is not fully supported, an error should be raised to avoid unnecessary debugging.

I have just tested that this works:

```python
class Book(LifecycleModelMixin, models.Model):
    title = models.CharField(max_length=200)
    previous_book = models.ForeignKey(
        "Book", null=True, blank=True, on_delete=models.CASCADE
    )

    @hook(AFTER_SAVE, when="previous_book", was=None, has_changed=True)
    def update_when_parent_is_set(self):
        print("Changing title")
```

Also, there's a specific section in the docs about [watching FK changes](https://rsinger86.github.io/django-lifecycle/fk_changes/).
