### ISSUE TITLE
Deleting model objects from Admin not triggering BEFORE_DELETE and AFTER_DELETE hooks

### ISSUE THREAD

**Issue by babus** [rsinger86/django-lifecycle#74]
Calling `model_object.delete()` successfully calls both BEFORE_DELETE and AFTER_DELETE hooks but if the same object is deleted from Django admin the hooks are not being called.

**Comment by eplutus** [comment]
I met the same issue but found out it had been explained and addressed by official Django doc: https://docs.djangoproject.com/en/dev/ref/contrib/admin/actions/#admin-actions

**Comment by EnriqueSoria** [comment]
As @eplutus said, this is a limitation of Django itself. It's explained [in the docs](https://docs.djangoproject.com/en/dev/ref/contrib/admin/actions/#admin-actions), and it says some possible workarounds.

I'm closing this as there's nothing more we can do.
