### ISSUE TITLE
Django 3.2 Support

### ISSUE THREAD

**Issue by JensAstrup** [rsinger86/django-lifecycle#88]
Is there a plan to officially support Django 3.2, one of the LTS versions? The package seems to work as-is, but it's not listed as supported which is causing some apprehension to using the package on my team. I'm happy to open a PR to add support if there isn't some reason that has been avoided.

**Comment by rsinger86** [comment]
my bad and thanks for the nudge... I'll make this explicit. 

my company has been using it in production with django 3.2 for a while now
